---
- hosts: localhost  # Assuming you're running Ansible locally
  connection: local
  become: true
     
  tasks:   
    - name: Docker build
      shell:
        cmd: |
          cd {{ workspace }}
          docker build --file Dockerfile --tag sharmi459/abc_tech:latest 
      vars:
        workspace: "{{ lookup('env', 'WORKSPACE') }}"
        
    - name: Push Docker image
      shell:
        cmd: |
          docker push docker.io/sharmi459/abc_tech:latest
