
kind: Deployment
apiVersion: apps/v1
metadata:
  name: abc-pod
  labels:
    app: abc_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc_app
  template:
    metadata:
      labels:
        app: abc_app
    spec:
      containers:
      - name: abc-technologies
        image: sharmi459/abc_tech:latest
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: abc-svc
spec:
  type: NodePort
  selector:
    app: abc_app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003
